<?php
    define('HOST','127.0.0.1');
    define('USER','root');
    define('KEY','');
    define('DB','ummat');
    define('EVENT_TABLE','event');
    define('DONATION_TABLE','donation');
    define('INBOX_TABLE','inbox');
    define('OUTBOX_TABLE','outbox');